export const countriesList = [
  {
    id: 17,
    name: "Bahrain",
    iso2: "BH",
    iso3: "BHR",
    phone_code: "+973",
    flag_url: "https://api.kintree.info/kintree-assets/images/countries/bh.png",
  },
  {
    id: 18,
    name: "Bangladesh",
    iso2: "BD",
    iso3: "BGD",
    phone_code: "+880",
    flag_url: "https://api.kintree.info/kintree-assets/images/countries/bd.png",
  },
  {
    id: 95,
    name: "India",
    iso2: "IN",
    iso3: "IND",
    phone_code: "+91",
    flag_url: "https://api.kintree.info/kintree-assets/images/countries/in.png",
  },
  {
    id: 96,
    name: "Indonesia",
    iso2: "ID",
    iso3: "IDN",
    phone_code: "+62",
    flag_url: "https://api.kintree.info/kintree-assets/images/countries/id.png",
  },
  {
    id: 97,
    name: "Iran",
    iso2: "IR",
    iso3: "IRN",
    phone_code: "+98",
    flag_url: "https://api.kintree.info/kintree-assets/images/countries/ir.png",
  },
  {
    id: 98,
    name: "Iraq",
    iso2: "IQ",
    iso3: "IRQ",
    phone_code: "+964",
    flag_url: "https://api.kintree.info/kintree-assets/images/countries/iq.png",
  },
  {
    id: 101,
    name: "Israel",
    iso2: "IL",
    iso3: "ISR",
    phone_code: "+972",
    flag_url: "https://api.kintree.info/kintree-assets/images/countries/il.png",
  },
  {
    id: 107,
    name: "Jordan",
    iso2: "JO",
    iso3: "JOR",
    phone_code: "+962",
    flag_url: "https://api.kintree.info/kintree-assets/images/countries/jo.png",
  },
  {
    id: 108,
    name: "Kazakhstan",
    iso2: "KZ",
    iso3: "KAZ",
    phone_code: "+7",
    flag_url: "https://api.kintree.info/kintree-assets/images/countries/kz.png",
  },
  {
    id: 112,
    name: "Kuwait",
    iso2: "KW",
    iso3: "KWT",
    phone_code: "+965",
    flag_url: "https://api.kintree.info/kintree-assets/images/countries/kw.png",
  },
  {
    id: 127,
    name: "Malaysia",
    iso2: "MY",
    iso3: "MYS",
    phone_code: "+60",
    flag_url: "https://api.kintree.info/kintree-assets/images/countries/my.png",
  },
  {
    id: 147,
    name: "Nepal",
    iso2: "NP",
    iso3: "NPL",
    phone_code: "+977",
    flag_url: "https://api.kintree.info/kintree-assets/images/countries/np.png",
  },
  {
    id: 159,
    name: "Oman",
    iso2: "OM",
    iso3: "OMN",
    phone_code: "+968",
    flag_url: "https://api.kintree.info/kintree-assets/images/countries/om.png",
  },
  {
    id: 160,
    name: "Pakistan",
    iso2: "PK",
    iso3: "PAK",
    phone_code: "+92",
    flag_url: "https://api.kintree.info/kintree-assets/images/countries/pk.png",
  },
  {
    id: 172,
    name: "Qatar",
    iso2: "QA",
    iso3: "QAT",
    phone_code: "+974",
    flag_url: "https://api.kintree.info/kintree-assets/images/countries/qa.png",
  },
  {
    id: 188,
    name: "Saudi Arabia",
    iso2: "SA",
    iso3: "SAU",
    phone_code: "+966",
    flag_url: "https://api.kintree.info/kintree-assets/images/countries/sa.png",
  },
  {
    id: 203,
    name: "Sri Lanka",
    iso2: "LK",
    iso3: "LKA",
    phone_code: "+94",
    flag_url: "https://api.kintree.info/kintree-assets/images/countries/lk.png",
  },
  {
    id: 214,
    name: "Thailand",
    iso2: "TH",
    iso3: "THA",
    phone_code: "+66",
    flag_url: "https://api.kintree.info/kintree-assets/images/countries/th.png",
  },
  {
    id: 220,
    name: "Turkey",
    iso2: "TR",
    iso3: "TUR",
    phone_code: "+90",
    flag_url: "https://api.kintree.info/kintree-assets/images/countries/tr.png",
  },
  {
    id: 227,
    name: "United Arab Emirates",
    iso2: "AE",
    iso3: "ARE",
    phone_code: "+971",
    flag_url: "https://api.kintree.info/kintree-assets/images/countries/ae.png",
  },
  {
    id: 238,
    name: "Yemen",
    iso2: "YE",
    iso3: "YEM",
    phone_code: "+967",
    flag_url: "https://api.kintree.info/kintree-assets/images/countries/ye.png",
  },
];
