import {
  route_foreroom,
  route_create_post,
  route_edit_post,
  route_view_post,
  route_create_poll,
  route_edit_poll,
  route_view_poll,
  route_family_tree_add_member,
  route_family_tree_view_member,
  route_family_tree_edit_member,
  route_login,
  route_register,
  route_forgot_password,
  route_forgot_username,
  route_family_tree,
  route_profile,
  route_chats,
  route_settings,
  route_notifications,
  route_events,
  route_events_create_event,
  route_events_edit_event,
  route_events_view_event,
  route_kincoins,
  route_will,
  route_family_member,
  route_kintree_member,
  route_tree_merge_request,
  route_astrology,
  route_horoscope,
  route_zodiac_sign,
  route_create_recipe,
  route_edit_recipe,
  route_view_recipe,
} from "./routeEnpoints";

const routeTitles = {
  [route_foreroom]: "Foreroom",
  [route_create_post]: "Create Post",
  [route_edit_post]: "Edit Post",
  [route_view_post]: "View Post",
  [route_create_poll]: "Create Poll",
  [route_edit_poll]: "Edit Poll",
  [route_view_poll]: "View Poll",
  [route_family_tree_add_member]: "Add Member",
  [route_family_tree_view_member]: "View Member",
  [route_family_tree_edit_member]: "Edit Member",
  [route_login]: "Login",
  [route_register]: "Register",
  [route_forgot_password]: "Forgot Password",
  [route_forgot_username]: "Forgot Username",
  [route_family_tree]: "Family Tree",
  [route_family_member]: "Family Member",
  [route_kintree_member]: "Kintree Member",
  [route_profile]: "Profile",
  [route_chats]: "Chats",
  [route_settings]: "Settings",
  [route_notifications]: "Notifications",
  [route_events]: "Events",
  [route_events_create_event]: "Create Event",
  [route_events_edit_event]: "Edit Event",
  [route_events_view_event]: "View Event",
  [route_kincoins]: "Kincoins",
  [route_will]: "Will",
  [route_tree_merge_request]: "Tree Merge Request",
  [route_astrology]: "Astrology",
  [route_horoscope]: "Horoscope",
  [route_zodiac_sign]: "Zodiac Sign",
  [route_create_recipe]: "Create Recipe",
  [route_edit_recipe]: "Edit Recipe",
  [route_view_recipe]: "View Recipe",
};

export default routeTitles;
