export const signSignList = [
  {
    id: 1,
    name: "aries",
    img_src: "/astrology-img/aries.svg",
    date: "Mar 21 - Apr 19",
    element: "Fire",
    polarity: "Positive",
    quality: "Cardinal",
    ruling_planet: "Mars",
    ruling_house: "First",
    spirit_color: "Red",
    lucky_gem: "Diamond",
    flower: "Thistle & honeysuckle",
    top_love_matches: "Sagittarius",
  },
  {
    id: 2,
    name: "taurus",
    img_src: "/astrology-img/taurus.svg",
    date: "Apr 20 - May 20",
    element: "Earth",
    polarity: "Negative",
    quality: "Fixed",
    ruling_planet: "Venus",
    ruling_house: "Second",
    spirit_color: "Pink",
    lucky_gem: "Emerald",
    flower: "Rose, Poppy, & Foxglove",
    top_love_matches: "Cancer & Virgo",
  },
  {
    id: 3,
    name: "gemini",
    img_src: "/astrology-img/gemini.svg",
    date: "May 21 - Jun 20",
    element: "Air",
    polarity: "Positive",
    quality: "Mutable",
    ruling_planet: "Mercury",
    ruling_house: "Third",
    spirit_color: "Yellow",
    lucky_gem: "Tiger's Eye & Emerald",
    flower: "Lavender & Lily of the Valley",
    top_love_matches: "Aries & Leo",
  },
  {
    id: 4,
    name: "cancer",
    img_src: "/astrology-img/cancer.svg",
    date: "Jun 21 - Jul 22",
    element: "Water",
    polarity: "Negative",
    quality: "Cardinal",
    ruling_planet: "Moon",
    ruling_house: "Fourth",
    spirit_color: "Violet",
    lucky_gem: "Ruby, pearl",
    flower: "Orchid and white rose",
    top_love_matches: "Taurus & Pisces",
  },
  {
    id: 5,
    name: "leo",
    img_src: "/astrology-img/leo.svg",
    date: "Jul 23 - Aug 22",
    element: "Fire",
    polarity: "Positive",
    quality: "Fixed",
    ruling_planet: "Sun",
    ruling_house: "Fifth",
    spirit_color: "Gold",
    lucky_gem: "Carnelian",
    flower: "Sunflower & marigold",
    top_love_matches: "Libra",
  },
  {
    id: 6,
    name: "virgo",
    img_src: "/astrology-img/virgo.svg",
    date: "Aug 23 - Sep 22",
    element: "Earth",
    polarity: "Negative",
    quality: "Mutable",
    ruling_planet: "Mercury",
    ruling_house: "Sixth",
    spirit_color: "Silver",
    lucky_gem: "Peridot",
    flower: "Sunflower & marigold",
    top_love_matches: "Cancer",
  },
  {
    id: 7,
    name: "libra",
    img_src: "/astrology-img/libra.svg",
    date: "Sep 23 - Oct 22",
    element: "Air",
    polarity: "Positive",
    quality: "Cardinal",
    ruling_planet: "Venus",
    ruling_house: "Seventh",
    spirit_color: "Blue",
    lucky_gem: "Sapphire",
    flower: "Rose",
    top_love_matches: "Gemini",
  },
  {
    id: 8,
    name: "scorpio",
    img_src: "/astrology-img/scorpio.svg",
    date: "Oct 23 - Nov 21",
    element: "Water",
    polarity: "Negative",
    quality: "Fixed",
    ruling_planet: "Pluto, Mars",
    ruling_house: "Eighth",
    spirit_color: "Black",
    lucky_gem: "Topaz & opal",
    flower: "Hibiscus & geraniums",
    top_love_matches: "Cancer",
  },
  {
    id: 9,
    name: "sagittarius",
    img_src: "/astrology-img/sagittarius.svg",
    date: "Nov 22 - Dec 21",
    element: "Fire",
    polarity: "Positive",
    quality: "Mutable",
    ruling_planet: "Jupiter",
    ruling_house: "Ninth",
    spirit_color: "Light Blue",
    lucky_gem: "Topaz",
    flower: "Carnations & crocuses",
    top_love_matches: "Aries",
  },
  {
    id: 10,
    name: "capricorn",
    img_src: "/astrology-img/capricorn.svg",
    date: "Dec 22 - Jan 19",
    element: "Earth",
    polarity: "Negative",
    quality: "Cardinal",
    ruling_planet: "Saturn",
    ruling_house: "Tenth",
    spirit_color: "Dark blue",
    lucky_gem: "Lapis lazuli",
    flower: "Pansy",
    top_love_matches: "Virgo",
  },
  {
    id: 11,
    name: "aquarius",
    img_src: "/astrology-img/aquarius.svg",
    date: "Jan 20 - Feb 18",
    element: "Air",
    polarity: "Positive",
    quality: "Fixed",
    ruling_planet: "Uranus",
    ruling_house: "Eleventh",
    spirit_color: "Sky blue",
    lucky_gem: "Amethyst",
    flower: "Orchid",
    top_love_matches: "Sagittarius",
  },
  {
    id: 12,
    name: "pisces",
    img_src: "/astrology-img/pisces.svg",
    date: "Feb 19 - Mar 20",
    element: "Water",
    polarity: "Negative",
    quality: "Mutable",
    ruling_planet: "Neptune",
    ruling_house: "Twelfth",
    spirit_color: "Sea green",
    lucky_gem: "Moonstone",
    flower: "Water lily",
    top_love_matches: "Virgo",
  },
];
